name: Lab 1

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  grade-labs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: ${{ github.ref }}

    - run: |
        git fetch origin team-0
        git clone --branch team-0 --single-branch . /tmp/team-0-branch

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        sudo apt install -y --no-install-recommends iverilog

    - name: Verify with cocotb & icarus
      run: |
        pytest /tmp/team-0-branch/miniALU/test /tmp/team-0-branch/slotMachine/test
