name: Lab 1

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  grade-labs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: ${{ github.ref }}

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Load Test Configuration from Branch
      id: load-config
      run: |
        CONFIG_FILE="./.github/workflows/test-config.txt"

        if [ ! -f $CONFIG_FILE ]; then
          echo "$CONFIG_FILE not found in branch."
          exit 1
        fi

        TEST_FILES=`sed -e 's%$%/test%' $CONFIG_FILE | tr '\n' ' '`

        echo "TEST_FILEPATH=$TEST_FILES" >> $GITHUB_ENV
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        sudo apt install -y --no-install-recommends iverilog

    - name: Verify with cocotb & icarus
      run: |
        git fetch origin team-0
        git clone --branch team-0 --single-branch https://github.com/8BitRobot/DAV-autograder.git ./tmp/
        cp -r -n -v ./tmp/ .
        find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
        echo "running tests in: $TEST_FILEPATH"
        pytest $TEST_FILEPATH
