name: Lab 1

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test-miniALU:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: ${{ github.ref }}

    - run: |
        git fetch origin team-0
        git clone --branch team-0 --single-branch https://github.com/8BitRobot/DAV-autograder.git /tmp/team-0-branch

    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        sudo apt install -y --no-install-recommends iverilog
        sudo apt install -y yq

    - name: Load Test Configuration from Branch
      id: load-config
      run: |
        CONFIG_FILE="./.github/workflows/test-config.yml"

        if [ ! -f $CONFIG_FILE ]; then
          echo "$CONFIG_FILE not found in branch."
          exit 1
        fi

        TEST-FILES=$(yq 'tests[]' $CONFIG_FILE | sed ':a;N;$!ba;s/\n/ /g')

        echo "::set-output name=test_files::$TEST_FILES"

    - name: Verify with cocotb & icarus
      run: |
        TEST_FILES="${{ steps.load-config.outputs.test_files }}"
        pytest --pyargs "/tmp/team-0-branch/$TEST_FILES"
